import type {
  App,
  Miner,
  Subscription,
  MiningProfile,
  DeveloperAnalytics,
  Developer,
  ProofSubmission,
  Withdrawal,
  Referral,
  HardwareProfile,
  ProofDetail,
  CollateralInfo,
  MiningProfileTrustScore,
  ProofStats,
} from "./types"

export const mockApps: App[] = [
  {
    id: "1",
    name: "Helium Network",
    description: "Decentralized wireless network for IoT devices. Earn HNT by providing network coverage.",
    category: "IoT",
    developer: "Helium Foundation",
    developerAddress: "0xHELI...a1b2",
    icon: "/logos/helium.png",
    status: "active",
    reputationScore: 98,
    totalMiners: 12453,
    totalEarnings: 2450000,
    avgEarningsPerDay: 45.5,
    requirements: {
      cpu: "2 cores",
      ram: "4GB",
      bandwidth: "10 Mbps",
    },
    resourceTypes: ["bandwidth", "data"],
    rewardToken: "HNT",
    createdAt: "2024-01-15",
    attestations: 156,
    tags: ["IoT", "Wireless", "Network"],
    consensusMechanism: "PoC",
    verificationMethod: "on-chain",
    rewardModel: "time-based",
    slaRequirements: {
      minUptime: 95,
      maxLatency: 500,
      minBandwidth: 10,
      proofSubmissionInterval: 3600,
      slashingPenalty: 5,
    },
    screenshots: ["/helium-network-coverage-map.jpg", "/helium-hotspot-dashboard.jpg"],
    features: [
      "Real-time coverage mapping",
      "Automatic proof of coverage",
      "Rewards tracking dashboard",
      "Network analytics",
    ],
    reviews: [
      {
        id: "r1",
        minerId: "miner-1",
        minerUsername: "MinerPro2024",
        appId: "1",
        rating: 5,
        comment: "Excellent network stability and consistent rewards. Best IoT network.",
        timestamp: "2024-03-15",
        helpful: 42,
      },
      {
        id: "r2",
        minerId: "miner-2",
        minerUsername: "DataMiner",
        appId: "1",
        rating: 4,
        comment: "Great rewards but setup was a bit complex.",
        timestamp: "2024-03-10",
        helpful: 28,
      },
    ],
    averageRating: 4.8,
    reviewCount: 128,
    monthlyGrowth: 12.5,
    trending: true,
    featured: true,
  },
  {
    id: "2",
    name: "Render Network",
    description: "Distributed GPU rendering for 3D graphics and AI workloads. Monetize your idle GPU power.",
    category: "AI/ML",
    developer: "Render Foundation",
    developerAddress: "0xRNDR...c3d4",
    icon: "/logos/render.png",
    status: "active",
    reputationScore: 95,
    totalMiners: 8932,
    totalEarnings: 1890000,
    avgEarningsPerDay: 125.0,
    requirements: {
      gpu: "NVIDIA RTX 3060+",
      cpu: "4 cores",
      ram: "16GB",
    },
    resourceTypes: ["compute"],
    rewardToken: "RNDR",
    createdAt: "2024-02-01",
    attestations: 203,
    tags: ["GPU", "Rendering", "AI"],
    consensusMechanism: "PoW",
    verificationMethod: "merkle-proof",
    attestationRequirements: ["TEE"],
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 98,
      maxLatency: 200,
      minBandwidth: 50,
      proofSubmissionInterval: 300,
      slashingPenalty: 10,
    },
    screenshots: ["/helium-hotspot-dashboard.jpg"],
    features: ["GPU rendering", "AI workload processing", "Task management dashboard"],
    reviews: [
      {
        id: "r3",
        minerId: "miner-3",
        minerUsername: "GraphicsPro",
        appId: "2",
        rating: 5,
        comment: "High performance and reliable rendering service.",
        timestamp: "2024-03-20",
        helpful: 35,
      },
      {
        id: "r4",
        minerId: "miner-4",
        minerUsername: "AIWorker",
        appId: "2",
        rating: 4,
        comment: "Good setup but needs more documentation.",
        timestamp: "2024-03-18",
        helpful: 22,
      },
    ],
    averageRating: 4.7,
    reviewCount: 105,
    monthlyGrowth: 15.2,
    trending: true,
  },
  {
    id: "3",
    name: "Filecoin Storage",
    description: "Decentralized storage project. Earn FIL by providing storage capacity to the network.",
    category: "Storage",
    developer: "Protocol Labs",
    developerAddress: "0xFILE...e5f6",
    icon: "/logos/filecoin.png",
    status: "active",
    reputationScore: 97,
    totalMiners: 15678,
    totalEarnings: 3200000,
    avgEarningsPerDay: 32.8,
    requirements: {
      storage: "1TB+",
      cpu: "8 cores",
      ram: "32GB",
      bandwidth: "100 Mbps",
    },
    resourceTypes: ["storage"],
    rewardToken: "FIL",
    createdAt: "2024-01-10",
    attestations: 289,
    tags: ["Storage", "IPFS", "Data"],
    consensusMechanism: "PoST",
    verificationMethod: "zk-proof",
    attestationRequirements: ["TPM"],
    rewardModel: "performance-based",
    slaRequirements: {
      minUptime: 99,
      maxLatency: 100,
      minBandwidth: 100,
      proofSubmissionInterval: 1800,
      slashingPenalty: 15,
    },
    screenshots: ["/theta-video-delivery-network.jpg"],
    features: ["Permanent storage", "IPFS compatibility", "Data retrieval"],
    reviews: [
      {
        id: "r5",
        minerId: "miner-5",
        minerUsername: "StoragePro",
        appId: "3",
        rating: 5,
        comment: "Excellent storage reliability and performance.",
        timestamp: "2024-03-25",
        helpful: 50,
      },
      {
        id: "r6",
        minerId: "miner-6",
        minerUsername: "DataKeeper",
        appId: "3",
        rating: 4,
        comment: "Good rewards but needs more user support.",
        timestamp: "2024-03-23",
        helpful: 30,
      },
    ],
    averageRating: 4.6,
    reviewCount: 118,
    monthlyGrowth: 10.1,
    trending: false,
  },
  {
    id: "4",
    name: "Akash Network",
    description: "Decentralized cloud compute marketplace. Lease your compute resources to developers.",
    category: "Compute",
    developer: "Akash Network",
    developerAddress: "0xAKSH...g7h8",
    icon: "/logos/akash.png",
    status: "active",
    reputationScore: 93,
    totalMiners: 5421,
    totalEarnings: 980000,
    avgEarningsPerDay: 78.5,
    requirements: {
      cpu: "8 cores",
      ram: "32GB",
      storage: "500GB",
      bandwidth: "50 Mbps",
    },
    resourceTypes: ["compute", "storage"],
    rewardToken: "AKT",
    createdAt: "2024-02-20",
    attestations: 134,
    tags: ["Cloud", "Compute", "Kubernetes"],
    consensusMechanism: "DPoS",
    verificationMethod: "tee-attestation",
    rewardModel: "time-based",
    slaRequirements: {
      minUptime: 97,
      maxLatency: 150,
      minBandwidth: 50,
      proofSubmissionInterval: 600,
      slashingPenalty: 8,
    },
    screenshots: ["/arweave-logo.jpg"],
    features: ["Kubernetes support", "Compute resource leasing", "Marketplace integration"],
    reviews: [
      {
        id: "r7",
        minerId: "miner-7",
        minerUsername: "CloudLeaser",
        appId: "4",
        rating: 5,
        comment: "Great platform for cloud resource leasing.",
        timestamp: "2024-03-30",
        helpful: 47,
      },
      {
        id: "r8",
        minerId: "miner-8",
        minerUsername: "ComputePro",
        appId: "4",
        rating: 4,
        comment: "User-friendly interface but needs more features.",
        timestamp: "2024-03-28",
        helpful: 33,
      },
    ],
    averageRating: 4.5,
    reviewCount: 92,
    monthlyGrowth: 7.8,
    trending: true,
  },
  {
    id: "5",
    name: "Ocean Protocol",
    description: "Decentralized data marketplace. Monetize your data while preserving privacy.",
    category: "Data Sovereignty",
    developer: "Ocean Protocol Foundation",
    developerAddress: "0xOCEA...i9j0",
    icon: "/logos/ocean.jpg",
    status: "active",
    reputationScore: 91,
    totalMiners: 3245,
    totalEarnings: 650000,
    avgEarningsPerDay: 55.2,
    requirements: {
      cpu: "4 cores",
      ram: "8GB",
      storage: "100GB",
    },
    resourceTypes: ["data", "storage"],
    rewardToken: "OCEAN",
    createdAt: "2024-03-05",
    attestations: 98,
    tags: ["Data", "Privacy", "AI"],
    consensusMechanism: "PoA",
    verificationMethod: "multi-sig",
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 90,
      maxLatency: 300,
      minBandwidth: 20,
      proofSubmissionInterval: 7200,
      slashingPenalty: 5,
    },
    screenshots: ["/storj-logo.jpg"],
    features: ["Data monetization", "Privacy-preserving", "AI-driven analytics"],
    reviews: [
      {
        id: "r9",
        minerId: "miner-9",
        minerUsername: "DataMonetizer",
        appId: "5",
        rating: 5,
        comment: "Excellent for data monetization and privacy.",
        timestamp: "2024-04-01",
        helpful: 44,
      },
      {
        id: "r10",
        minerId: "miner-10",
        minerUsername: "PrivacyPro",
        appId: "5",
        rating: 4,
        comment: "Good platform but needs more tutorials.",
        timestamp: "2024-03-31",
        helpful: 38,
      },
    ],
    averageRating: 4.4,
    reviewCount: 86,
    monthlyGrowth: 6.9,
    trending: false,
  },
  {
    id: "6",
    name: "Livepeer Network",
    description: "Decentralized video transcoding project. Earn LPT by processing video streams.",
    category: "Compute",
    developer: "Livepeer Inc",
    developerAddress: "0xLIVE...k1l2",
    icon: "/logos/livepeer.png",
    status: "active",
    reputationScore: 94,
    totalMiners: 4567,
    totalEarnings: 1100000,
    avgEarningsPerDay: 92.3,
    requirements: {
      cpu: "8 cores",
      gpu: "NVIDIA GTX 1060+",
      ram: "16GB",
      bandwidth: "100 Mbps",
    },
    resourceTypes: ["compute", "bandwidth"],
    rewardToken: "LPT",
    createdAt: "2024-01-25",
    attestations: 167,
    tags: ["Video", "Streaming", "Transcoding"],
    consensusMechanism: "DPoS",
    verificationMethod: "on-chain",
    rewardModel: "performance-based",
    slaRequirements: {
      minUptime: 96,
      maxLatency: 250,
      minBandwidth: 100,
      proofSubmissionInterval: 900,
      slashingPenalty: 12,
    },
    screenshots: ["/golem-logo.jpg"],
    features: ["Video transcoding", "Compute resource utilization", "Task scheduling"],
    reviews: [
      {
        id: "r11",
        minerId: "miner-11",
        minerUsername: "VideoTranscoder",
        appId: "6",
        rating: 5,
        comment: "High-quality video transcoding and reliable service.",
        timestamp: "2024-04-05",
        helpful: 52,
      },
      {
        id: "r12",
        minerId: "miner-12",
        minerUsername: "StreamPro",
        appId: "6",
        rating: 4,
        comment: "Good rewards but needs more user support.",
        timestamp: "2024-04-04",
        helpful: 36,
      },
    ],
    averageRating: 4.6,
    reviewCount: 100,
    monthlyGrowth: 14.3,
    trending: true,
  },
  {
    id: "7",
    name: "Theta Network",
    description: "Decentralized video delivery and edge computing. Earn THETA by sharing bandwidth.",
    category: "Content Delivery",
    developer: "Theta Labs",
    developerAddress: "0xTHET...m3n4",
    icon: "/logos/theta.png",
    status: "active",
    reputationScore: 96,
    totalMiners: 9876,
    totalEarnings: 1650000,
    avgEarningsPerDay: 88.3,
    requirements: {
      bandwidth: "25 Mbps",
      cpu: "4 cores",
      ram: "8GB",
    },
    resourceTypes: ["bandwidth", "compute"],
    rewardToken: "THETA",
    createdAt: "2024-02-10",
    attestations: 145,
    tags: ["Video", "CDN", "Streaming"],
    consensusMechanism: "DPoS",
    verificationMethod: "on-chain",
    rewardModel: "time-based",
    slaRequirements: {
      minUptime: 94,
      maxLatency: 400,
      minBandwidth: 25,
      proofSubmissionInterval: 1800,
      slashingPenalty: 7,
    },
    screenshots: ["/theta-video-delivery-network.jpg"],
    features: ["Video streaming", "Edge caching", "Bandwidth rewards"],
    reviews: [
      {
        id: "r13",
        minerId: "miner-13",
        minerUsername: "ThetaUser",
        appId: "7",
        rating: 5,
        comment: "Excellent video delivery and edge computing service.",
        timestamp: "2024-04-10",
        helpful: 49,
      },
      {
        id: "r14",
        minerId: "miner-14",
        minerUsername: "EdgePro",
        appId: "7",
        rating: 4,
        comment: "Good rewards but needs more user support.",
        timestamp: "2024-04-09",
        helpful: 34,
      },
    ],
    averageRating: 4.5,
    reviewCount: 90,
    monthlyGrowth: 8.2,
    trending: false,
  },
  {
    id: "8",
    name: "Arweave",
    description: "Permanent data storage on blockchain. Get paid to store data forever.",
    category: "Storage",
    developer: "Arweave Team",
    developerAddress: "0xARWE...o5p6",
    icon: "/logos/arweave.jpg",
    status: "active",
    reputationScore: 97,
    totalMiners: 7654,
    totalEarnings: 2100000,
    avgEarningsPerDay: 62.4,
    requirements: {
      storage: "2TB+",
      cpu: "4 cores",
      ram: "16GB",
    },
    resourceTypes: ["storage"],
    rewardToken: "AR",
    createdAt: "2024-01-20",
    attestations: 178,
    tags: ["Storage", "Blockchain", "Permanent"],
    consensusMechanism: "PoC",
    verificationMethod: "merkle-proof",
    rewardModel: "storage-based",
    slaRequirements: {
      minUptime: 99,
      maxLatency: 200,
      minBandwidth: 50,
      proofSubmissionInterval: 2400,
      slashingPenalty: 12,
    },
    screenshots: [],
    features: ["Permanent storage", "Blockweave technology", "Weave query"],
    reviews: [
      {
        id: "r-8-1",
        minerId: "miner_x7k2p",
        minerUsername: "PermanentVault",
        appId: "8",
        rating: 5,
        comment: "Genuinely passive income once your node is set up. I'm running 4TB on Arweave and the weave rewards have been consistent for 8 months straight. The blockweave architecture means your data never goes offline — clients love that guarantee.",
        timestamp: "2025-09-14",
        helpful: 67,
      },
      {
        id: "r-8-2",
        minerId: "miner_q9n4t",
        minerUsername: "StorageFarmer99",
        appId: "8",
        rating: 5,
        comment: "Best ROI of any storage protocol I've tried. Initial hardware investment pays back in under 6 months at current AR prices. Merkle proof verification is clean and I've had zero slashing events.",
        timestamp: "2025-11-02",
        helpful: 53,
      },
      {
        id: "r-8-3",
        minerId: "miner_b3m7w",
        minerUsername: "DataArchitect",
        appId: "8",
        rating: 4,
        comment: "Solid protocol with strong fundamentals. Reward consistency is excellent and the permanent storage pitch attracts serious enterprise clients. Docking one star only because initial sync of the weave takes forever on a fresh node.",
        timestamp: "2025-12-18",
        helpful: 41,
      },
      {
        id: "r-8-4",
        minerId: "miner_h6v1s",
        minerUsername: "NVMeKing",
        appId: "8",
        rating: 4,
        comment: "Running 8TB across two nodes. Earnings are predictable and the storage-based reward model rewards scale well. Community Discord is helpful for troubleshooting sync issues.",
        timestamp: "2026-01-07",
        helpful: 29,
      },
      {
        id: "r-8-5",
        minerId: "miner_c2f8d",
        minerUsername: "WeaveRunner",
        appId: "8",
        rating: 5,
        comment: "Three months in and earnings exceed my electricity costs by 4x. The weave query feature alone is a differentiator. Enterprise adoption is accelerating which keeps demand for storage high.",
        timestamp: "2026-02-20",
        helpful: 38,
      },
    ],
    averageRating: 4.7,
    reviewCount: 112,
    monthlyGrowth: 5.8,
    trending: true,
  },
  {
    id: "9",
    name: "Storj",
    description: "Decentralized cloud storage. Rent unused hard drive space.",
    category: "Storage",
    developer: "Storj Labs",
    developerAddress: "0xSTRJ...q7r8",
    icon: "/logos/storj.png",
    status: "active",
    reputationScore: 94,
    totalMiners: 11234,
    totalEarnings: 1850000,
    avgEarningsPerDay: 42.7,
    requirements: {
      storage: "500GB+",
      cpu: "2 cores",
      ram: "8GB",
      bandwidth: "10 Mbps",
    },
    resourceTypes: ["storage"],
    rewardToken: "STORJ",
    createdAt: "2024-02-05",
    attestations: 134,
    tags: ["Cloud Storage", "S3-compatible"],
    consensusMechanism: "DPoS",
    verificationMethod: "tee-attestation",
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 99.5,
      maxLatency: 150,
      minBandwidth: 10,
      proofSubmissionInterval: 3600,
      slashingPenalty: 20,
    },
    screenshots: [],
    features: ["Encryption", "Redundancy", "Bandwidth rewards"],
    reviews: [
      {
        id: "r-9-1",
        minerId: "miner_y4r2c",
        minerUsername: "StorjNodeOp",
        appId: "9",
        rating: 5,
        comment: "S3-compatible API means customers flow in constantly. My 2TB node earns reliably every month and the client software is dead simple to configure. Storj is the most beginner-friendly storage protocol I've used.",
        timestamp: "2025-08-05",
        helpful: 58,
      },
      {
        id: "r-9-2",
        minerId: "miner_p0k6j",
        minerUsername: "RedundancyMax",
        appId: "9",
        rating: 4,
        comment: "Strong vetting process before you get traffic — they test your uptime hard. But once you pass it's smooth sailing. End-to-end encryption gives enterprise clients confidence which drives demand.",
        timestamp: "2025-10-12",
        helpful: 44,
      },
      {
        id: "r-9-3",
        minerId: "miner_d8t5l",
        minerUsername: "BandwidthArb",
        appId: "9",
        rating: 4,
        comment: "Good earnings for the hardware requirement. 500GB minimum is low enough to onboard on a spare drive. The bandwidth reward on top of storage is a nice bonus that most protocols skip.",
        timestamp: "2025-12-03",
        helpful: 33,
      },
      {
        id: "r-9-4",
        minerId: "miner_w1e9g",
        minerUsername: "CloudNative",
        appId: "9",
        rating: 5,
        comment: "Running Storj on a home server with 6TB allocated. Uptime requirement of 99.5% is achievable on decent hardware and earnings are consistent. Documentation is thorough and the community is knowledgeable.",
        timestamp: "2026-01-15",
        helpful: 47,
      },
      {
        id: "r-9-5",
        minerId: "miner_f5u3x",
        minerUsername: "SatoshiStorage",
        appId: "9",
        rating: 3,
        comment: "Decent protocol but earnings are lower than Arweave or Filecoin per TB stored. Uptime requirement of 99.5% is punishing if you have power outages. Worth running if you have reliable infrastructure already.",
        timestamp: "2026-02-28",
        helpful: 22,
      },
    ],
    averageRating: 4.5,
    reviewCount: 89,
    monthlyGrowth: 3.2,
    trending: false,
  },
  {
    id: "10",
    name: "Golem Network",
    description: "Decentralized compute marketplace. Rent your CPU for tasks.",
    category: "Compute",
    developer: "Golem Factory",
    developerAddress: "0xGOLM...s9t0",
    icon: "/logos/golem.png",
    status: "active",
    reputationScore: 92,
    totalMiners: 6789,
    totalEarnings: 890000,
    avgEarningsPerDay: 95.2,
    requirements: {
      cpu: "8 cores",
      ram: "32GB",
      storage: "100GB",
    },
    resourceTypes: ["compute"],
    rewardToken: "GLM",
    createdAt: "2024-03-01",
    attestations: 98,
    tags: ["Compute", "Distributed Computing"],
    consensusMechanism: "Custom",
    verificationMethod: "custom",
    rewardModel: "performance-based",
    slaRequirements: {
      minUptime: 95,
      maxLatency: 500,
      minBandwidth: 20,
      proofSubmissionInterval: 1200,
      slashingPenalty: 8,
    },
    screenshots: [],
    features: ["Task execution", "Verification layer", "Payment channel"],
    reviews: [
      {
        id: "r-10-1",
        minerId: "miner_a9c4m",
        minerUsername: "GolemWorker",
        appId: "10",
        rating: 4,
        comment: "Golem's task marketplace is diversifying fast — I'm seeing rendering jobs, AI inference, and scientific compute all flowing through. The custom verification layer is solid and payment channels keep gas costs low.",
        timestamp: "2025-09-22",
        helpful: 49,
      },
      {
        id: "r-10-2",
        minerId: "miner_k3n8b",
        minerUsername: "CPUFarm",
        appId: "10",
        rating: 5,
        comment: "Repurposed my old workstation (32-core Threadripper) for Golem and it's printing GLM. Performance-based rewards mean my fast CPU earns more per task than competitors. 15.6% monthly growth is real — I see it in my earnings.",
        timestamp: "2025-11-08",
        helpful: 62,
      },
      {
        id: "r-10-3",
        minerId: "miner_r7h2v",
        minerUsername: "DistributedOps",
        appId: "10",
        rating: 4,
        comment: "Custom consensus and verification is flexible but docs could be better. Once you understand the task pipeline it's quite robust. My 32GB RAM node handles mixed workloads well and earnings beat most compute protocols.",
        timestamp: "2025-12-14",
        helpful: 35,
      },
      {
        id: "r-10-4",
        minerId: "miner_e1s6p",
        minerUsername: "TaskRunner",
        appId: "10",
        rating: 3,
        comment: "Solid foundation but task availability varies by time zone — dead hours in the middle of the night US time. The verification layer occasionally bounces valid results which is frustrating. Team seems to be improving it though.",
        timestamp: "2026-01-20",
        helpful: 28,
      },
      {
        id: "r-10-5",
        minerId: "miner_j0f4w",
        minerUsername: "GridMiner",
        appId: "10",
        rating: 5,
        comment: "Golem has the best GLM/hour rate I've measured across all compute protocols. Payment channels are near-instant which matters for cash flow. Highly recommend for anyone with CPU-heavy hardware sitting idle.",
        timestamp: "2026-03-01",
        helpful: 44,
      },
    ],
    averageRating: 4.3,
    reviewCount: 67,
    monthlyGrowth: 15.6,
    trending: true,
  },
  {
    id: "11",
    name: "The Graph",
    description: "Decentralized indexing protocol. Index blockchain data and earn.",
    category: "Data Sovereignty",
    developer: "The Graph Foundation",
    developerAddress: "0xGRPH...u1v2",
    icon: "/logos/the-graph.png",
    status: "active",
    reputationScore: 96,
    totalMiners: 4532,
    totalEarnings: 1230000,
    avgEarningsPerDay: 110.5,
    requirements: {
      cpu: "16 cores",
      ram: "64GB",
      storage: "2TB",
      bandwidth: "100 Mbps",
    },
    resourceTypes: ["compute", "data"],
    rewardToken: "GRT",
    createdAt: "2024-01-30",
    attestations: 156,
    tags: ["Indexing", "GraphQL", "Blockchain"],
    consensusMechanism: "DPoS",
    verificationMethod: "on-chain",
    attestationRequirements: ["TEE", "TPM"],
    rewardModel: "stake-weighted",
    slaRequirements: {
      minUptime: 99.9,
      maxLatency: 50,
      minBandwidth: 100,
      proofSubmissionInterval: 600,
      slashingPenalty: 25,
    },
    screenshots: [],
    features: ["GraphQL API", "Subgraph hosting", "Indexing rewards"],
    reviews: [
      {
        id: "r-11-1",
        minerId: "miner_z5t9k",
        minerUsername: "IndexerPrime",
        appId: "11",
        rating: 5,
        comment: "The Graph is the backbone of DeFi and my indexer node has been running for over a year without issues. Stake-weighted rewards scale beautifully as I add GRT. Query fees are climbing as subgraph usage grows — this is the one to hold long-term.",
        timestamp: "2025-08-18",
        helpful: 91,
      },
      {
        id: "r-11-2",
        minerId: "miner_u2m7r",
        minerUsername: "GraphNodeRunner",
        appId: "11",
        rating: 5,
        comment: "22% monthly growth is not a fluke — I've watched indexer demand expand consistently. The hardware requirements are high (64GB RAM, 2TB) but the GRT rewards justify premium hardware investment. Best reputation score in my portfolio.",
        timestamp: "2025-10-05",
        helpful: 78,
      },
      {
        id: "r-11-3",
        minerId: "miner_i8g3n",
        minerUsername: "SubgraphDev",
        appId: "11",
        rating: 5,
        comment: "Running an indexer and developing subgraphs simultaneously. The dual-sided incentives are unique in the space. On-chain verification means zero disputes. The slashing penalty is steep (25%) but honest operators never get touched.",
        timestamp: "2025-11-30",
        helpful: 56,
      },
      {
        id: "r-11-4",
        minerId: "miner_o4b1y",
        minerUsername: "QueryCurator",
        appId: "11",
        rating: 4,
        comment: "Excellent protocol with tight SLA requirements — 99.9% uptime and <50ms latency demands enterprise-grade infrastructure. Once you invest in the setup, rewards are very competitive. TEE + TPM attestation requirement adds trust for curators.",
        timestamp: "2026-01-12",
        helpful: 43,
      },
      {
        id: "r-11-5",
        minerId: "miner_v6c2l",
        minerUsername: "DeFiIndexer",
        appId: "11",
        rating: 5,
        comment: "My indexer node earns more GRT per day than any other protocol I run. The GraphQL API tooling is mature and debugging is straightforward. 145 reviews here and the average is 4.9 for good reason.",
        timestamp: "2026-02-14",
        helpful: 67,
      },
    ],
    averageRating: 4.9,
    reviewCount: 145,
    monthlyGrowth: 22.3,
    trending: true,
  },
  {
    id: "12",
    name: "Chainlink",
    description: "Decentralized oracle project. Run a node and earn LINK.",
    category: "Blockchain",
    developer: "Chainlink Labs",
    developerAddress: "0xLINK...w3x4",
    icon: "/logos/chainlink.png",
    status: "active",
    reputationScore: 99,
    totalMiners: 8765,
    totalEarnings: 3450000,
    avgEarningsPerDay: 175.3,
    requirements: {
      cpu: "4 cores",
      ram: "8GB",
      storage: "50GB",
    },
    resourceTypes: ["data"],
    rewardToken: "LINK",
    createdAt: "2023-12-15",
    attestations: 267,
    tags: ["Oracle", "Data feeds", "Blockchain"],
    consensusMechanism: "PoS",
    verificationMethod: "on-chain",
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 99.95,
      maxLatency: 10,
      minBandwidth: 25,
      proofSubmissionInterval: 60,
      slashingPenalty: 30,
    },
    screenshots: [],
    features: ["Price feeds", "VRF", "Automation"],
    reviews: [
      {
        id: "r-12-1",
        minerId: "miner_t3k9w",
        minerUsername: "OracleOperator",
        appId: "12",
        rating: 5,
        comment: "Chainlink is the gold standard of oracle networks and running a node proves it. My node has been live since January 2024 and I have not missed a single data feed. The 99.95% uptime requirement keeps bad actors out and rewards the committed.",
        timestamp: "2025-07-28",
        helpful: 103,
      },
      {
        id: "r-12-2",
        minerId: "miner_n1p5v",
        minerUsername: "LinkMaximalist",
        appId: "12",
        rating: 5,
        comment: "Best earnings-per-day of any non-GPU protocol at $175 average. Per-task model rewards responsiveness — if your node is fast you earn more. VRF jobs pay premium rates. The slashing penalty is severe but I respect the network discipline.",
        timestamp: "2025-09-17",
        helpful: 89,
      },
      {
        id: "r-12-3",
        minerId: "miner_s8e2d",
        minerUsername: "PriceFeedPro",
        appId: "12",
        rating: 5,
        comment: "Running a Chainlink node requires only modest hardware (4 cores, 8GB RAM) compared to the LINK rewards. The automation jobs are steady income on top of price feeds. 267 attestations tells you how trusted this network is.",
        timestamp: "2025-11-22",
        helpful: 74,
      },
      {
        id: "r-12-4",
        minerId: "miner_l6h4f",
        minerUsername: "DecentralOracle",
        appId: "12",
        rating: 5,
        comment: "Chainlink's on-chain verification is transparent and trustless. The 60-second proof submission interval keeps you honest and the rewards reflect that rigor. For anyone with reliable infrastructure this is a no-brainer primary protocol.",
        timestamp: "2026-01-08",
        helpful: 61,
      },
      {
        id: "r-12-5",
        minerId: "miner_g2r7m",
        minerUsername: "NodeTech88",
        appId: "12",
        rating: 4,
        comment: "Near perfect protocol. Only suggestion is better tooling for monitoring multiple jobs simultaneously. The earning rate is exceptional and the LINK token has proven itself over years of market volatility. Tier-1 protocol for any serious miner.",
        timestamp: "2026-02-19",
        helpful: 52,
      },
    ],
    averageRating: 4.95,
    reviewCount: 287,
    monthlyGrowth: 8.5,
    featured: true,
  },
  {
    id: "13",
    name: "IoTeX",
    description: "IoT-friendly blockchain. Build IoT machines on Web3.",
    category: "IoT",
    developer: "IoTeX Foundation",
    developerAddress: "0xIOTX...y5z6",
    icon: "/logos/iotex.png",
    status: "active",
    reputationScore: 91,
    totalMiners: 3421,
    totalEarnings: 540000,
    avgEarningsPerDay: 48.2,
    requirements: {
      cpu: "2 cores",
      ram: "4GB",
      storage: "20GB",
    },
    resourceTypes: ["bandwidth", "data"],
    rewardToken: "IOTX",
    createdAt: "2024-02-28",
    attestations: 76,
    tags: ["IoT", "Blockchain", "Devices"],
    consensusMechanism: "DPoS",
    verificationMethod: "custom",
    rewardModel: "time-based",
    slaRequirements: {
      minUptime: 92,
      maxLatency: 600,
      minBandwidth: 5,
      proofSubmissionInterval: 7200,
      slashingPenalty: 3,
    },
    screenshots: [],
    features: ["IoT protocols", "Device registration", "Data marketplace"],
    reviews: [
      {
        id: "r-13-1",
        minerId: "miner_c7j3x",
        minerUsername: "IoTEnthusiast",
        appId: "13",
        rating: 5,
        comment: "Running IoTeX on a small Raspberry Pi cluster — the lightweight requirements (2 cores, 4GB RAM) make it perfect for low-power hardware. IOTX rewards are solid and the IoT data marketplace adds a second revenue stream I wasn't expecting.",
        timestamp: "2025-08-30",
        helpful: 37,
      },
      {
        id: "r-13-2",
        minerId: "miner_p4b9k",
        minerUsername: "MachineEconomy",
        appId: "13",
        rating: 4,
        comment: "Solid protocol for the IoT vertical. Device registration flow is smooth and the blockchain integration is mature. Monthly growth of 11% is visible in my IOTX earnings trending up quarter over quarter.",
        timestamp: "2025-10-20",
        helpful: 29,
      },
      {
        id: "r-13-3",
        minerId: "miner_h0n6t",
        minerUsername: "EdgeDevice",
        appId: "13",
        rating: 4,
        comment: "Good fit for miners who already have IoT infrastructure. The DPoS mechanism keeps the network efficient and the time-based reward model means uptime is your main lever. Community is helpful for first-time node setup.",
        timestamp: "2025-12-07",
        helpful: 21,
      },
      {
        id: "r-13-4",
        minerId: "miner_w8s2q",
        minerUsername: "Pebble2024",
        appId: "13",
        rating: 5,
        comment: "IoTeX pairs well with physical IoT deployments. I run environmental sensor nodes and the verified on-chain data commands premium rates in the marketplace. Flexible latency requirements (600ms) accommodate real-world IoT constraints.",
        timestamp: "2026-01-25",
        helpful: 33,
      },
      {
        id: "r-13-5",
        minerId: "miner_f3v1r",
        minerUsername: "SmartHomeMiner",
        appId: "13",
        rating: 4,
        comment: "Great for IoT-native builders. Custom verification is a double-edged sword — flexible but requires more due diligence. Earnings are modest compared to GPU protocols but the hardware cost is tiny.",
        timestamp: "2026-02-10",
        helpful: 18,
      },
    ],
    averageRating: 4.4,
    reviewCount: 54,
    monthlyGrowth: 11.2,
  },
  {
    id: "14",
    name: "0x Protocol",
    description: "Decentralized exchange protocol. Run relayers and earn.",
    category: "Blockchain",
    developer: "0x Labs",
    developerAddress: "0x00ZX...a7b8",
    icon: "/logos/0x.png",
    status: "active",
    reputationScore: 95,
    totalMiners: 5678,
    totalEarnings: 1450000,
    avgEarningsPerDay: 120.4,
    requirements: {
      cpu: "4 cores",
      ram: "16GB",
      storage: "100GB",
      bandwidth: "50 Mbps",
    },
    resourceTypes: ["compute", "bandwidth"],
    rewardToken: "ZRX",
    createdAt: "2024-01-05",
    attestations: 123,
    tags: ["DEX", "Trading", "Liquidity"],
    consensusMechanism: "Custom",
    verificationMethod: "on-chain",
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 98,
      maxLatency: 100,
      minBandwidth: 50,
      proofSubmissionInterval: 300,
      slashingPenalty: 15,
    },
    screenshots: [],
    features: ["Order matching", "Liquidity pools", "Cross-chain trades"],
    reviews: [
      {
        id: "r-14-1",
        minerId: "miner_d2k8y",
        minerUsername: "RelayerOne",
        appId: "14",
        rating: 5,
        comment: "Running a 0x relayer is essentially running a DEX front-end with fee income. The ZRX per-task rewards on top of trading fees make this the best dual-income compute protocol I've found. Cross-chain feature is driving significant volume.",
        timestamp: "2025-09-04",
        helpful: 54,
      },
      {
        id: "r-14-2",
        minerId: "miner_b9g1e",
        minerUsername: "LiquidityOps",
        appId: "14",
        rating: 4,
        comment: "Solid rewards for bandwidth and compute investment. The 300-second proof submission keeps the protocol honest. On-chain verification means no dispute headaches. Bandwidth requirement of 50 Mbps is standard for any decent home setup.",
        timestamp: "2025-11-16",
        helpful: 39,
      },
      {
        id: "r-14-3",
        minerId: "miner_q5m3c",
        minerUsername: "DEXRunner",
        appId: "14",
        rating: 5,
        comment: "ZRX rewards have been climbing alongside DeFi volume growth. The order matching workload is CPU-light which means high profit margin. Monthly growth of 9.4% is consistent and I expect it to accelerate as cross-chain DEX usage expands.",
        timestamp: "2026-01-03",
        helpful: 46,
      },
      {
        id: "r-14-4",
        minerId: "miner_x6p2n",
        minerUsername: "ArbitrageNode",
        appId: "14",
        rating: 4,
        comment: "Good earnings and the custom consensus adds operational flexibility. Would benefit from a native dashboard for monitoring order flow per relayer. That said, the raw ZRX income is reliable and the protocol team is responsive.",
        timestamp: "2026-02-22",
        helpful: 27,
      },
    ],
    averageRating: 4.6,
    reviewCount: 78,
    monthlyGrowth: 9.4,
  },
  {
    id: "15",
    name: "Hivemapper",
    description: "Decentralized mapping project. Earn HONEY by contributing dashcam footage to build real-time maps.",
    category: "DePIN",
    developer: "Hivemapper Inc",
    developerAddress: "0xHIVE...c9d0",
    icon: "/logos/hivemapper.png",
    status: "active",
    reputationScore: 89,
    totalMiners: 18500,
    totalEarnings: 2100000,
    avgEarningsPerDay: 28.5,
    requirements: {
      cpu: "2 cores",
      ram: "4GB",
      storage: "64GB",
      bandwidth: "10 Mbps",
    },
    resourceTypes: ["data", "bandwidth"],
    rewardToken: "HONEY",
    createdAt: "2024-03-01",
    attestations: 167,
    tags: ["Mapping", "DePIN", "Data"],
    consensusMechanism: "PoC",
    verificationMethod: "on-chain",
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 80,
      maxLatency: 1000,
      minBandwidth: 10,
      proofSubmissionInterval: 86400,
      slashingPenalty: 2,
    },
    screenshots: [],
    features: ["Real-time map updates", "AI image processing", "Fleet management"],
    reviews: [
      {
        id: "r-15-1",
        minerId: "miner_r4t0k",
        minerUsername: "DashcamMiner",
        appId: "15",
        rating: 5,
        comment: "Mounted the Hivemapper dashcam on my truck — it earns HONEY on every mile I drive for work anyway. Zero extra effort required. In dense urban areas earnings are noticeably higher due to map update demand. 25% monthly growth matches my experience.",
        timestamp: "2025-08-10",
        helpful: 83,
      },
      {
        id: "r-15-2",
        minerId: "miner_c7u5n",
        minerUsername: "MapperFleet",
        appId: "15",
        rating: 4,
        comment: "Running a 3-vehicle delivery fleet on Hivemapper. The fleet management dashboard is genuinely useful and AI image processing quality has improved dramatically over the past year. HONEY tokenomics are still maturing but trajectory is positive.",
        timestamp: "2025-10-27",
        helpful: 68,
      },
      {
        id: "r-15-3",
        minerId: "miner_v1w8j",
        minerUsername: "CoverageHunter",
        appId: "15",
        rating: 4,
        comment: "The PoC model rewards unique roads you map — if you drive routes nobody else covers you earn a multiplier. Smart incentive design. Coverage in my suburban area was sparse so I had strong earnings early on. Now more competition but still profitable.",
        timestamp: "2025-12-09",
        helpful: 55,
      },
      {
        id: "r-15-4",
        minerId: "miner_k9e3s",
        minerUsername: "RoadData",
        appId: "15",
        rating: 3,
        comment: "Concept is brilliant but earnings per mile are lower than expected in densely mapped urban cores. The dashcam hardware cost ($350+) takes a few months to recover. Rural miners seem to earn significantly more per hour of driving.",
        timestamp: "2026-01-18",
        helpful: 44,
      },
      {
        id: "r-15-5",
        minerId: "miner_m2d6p",
        minerUsername: "HoneyCollector",
        appId: "15",
        rating: 5,
        comment: "This is the best DePIN protocol for people without server hardware. Your car does the mining. Set up took 15 minutes and I've earned HONEY every day since without any maintenance. The 18,500 miner count proves this works at scale.",
        timestamp: "2026-02-05",
        helpful: 72,
      },
    ],
    averageRating: 4.3,
    reviewCount: 245,
    monthlyGrowth: 25.3,
    trending: true,
  },
  {
    id: "16",
    name: "Bittensor",
    description: "Decentralized AI project. Contribute compute power for machine learning and earn TAO.",
    category: "AI/ML",
    developer: "Opentensor Foundation",
    developerAddress: "0xBTSR...e1f2",
    icon: "/logos/bittensor.jpg",
    status: "active",
    reputationScore: 94,
    totalMiners: 7800,
    totalEarnings: 4500000,
    avgEarningsPerDay: 185.0,
    requirements: {
      gpu: "NVIDIA RTX 3080+",
      cpu: "8 cores",
      ram: "64GB",
      storage: "500GB",
    },
    resourceTypes: ["compute"],
    rewardToken: "TAO",
    createdAt: "2024-01-20",
    attestations: 189,
    tags: ["AI", "Machine Learning", "Neural Networks"],
    consensusMechanism: "PoW",
    verificationMethod: "custom",
    attestationRequirements: ["SGX"],
    rewardModel: "performance-based",
    slaRequirements: {
      minUptime: 95,
      maxLatency: 300,
      minBandwidth: 100,
      proofSubmissionInterval: 600,
      slashingPenalty: 15,
    },
    screenshots: [],
    features: ["Subnet mining", "Model validation", "Incentivized learning"],
    reviews: [
      {
        id: "r-16-1",
        minerId: "miner_a8x2n",
        minerUsername: "TaoMiner",
        appId: "16",
        rating: 5,
        comment: "Bittensor is unlike any other mining protocol — you're actually contributing to AI model improvement, not just serving storage or bandwidth. My RTX 3090 runs subnet 1 (text completion) and earnings have 5x'd in 8 months as TAO price climbed.",
        timestamp: "2025-07-20",
        helpful: 112,
      },
      {
        id: "r-16-2",
        minerId: "miner_h3j7v",
        minerUsername: "SubnetSpecialist",
        appId: "16",
        rating: 5,
        comment: "The subnet system is genius — different subnets optimize for different AI tasks so you can specialize. SGX attestation requirement is a high bar but it filters out low-quality validators. 32% monthly growth is the highest I've seen on any protocol.",
        timestamp: "2025-09-11",
        helpful: 94,
      },
      {
        id: "r-16-3",
        minerId: "miner_q5r0b",
        minerUsername: "ModelValidator",
        appId: "16",
        rating: 4,
        comment: "Legitimate AI compute, not just pretend workloads. You compete against other miners on model quality scores which creates a real market for GPU performance. 64GB RAM requirement is steep but the TAO earnings at $185/day justify high-end hardware.",
        timestamp: "2025-11-25",
        helpful: 71,
      },
      {
        id: "r-16-4",
        minerId: "miner_f7k1c",
        minerUsername: "NeuralMiner",
        appId: "16",
        rating: 5,
        comment: "Performance-based rewards mean smarter/faster hardware wins. I upgraded to an RTX 4090 and earnings jumped 40%. The incentivized learning framework is academically sound — validators actually test model outputs, not just uptime.",
        timestamp: "2026-01-30",
        helpful: 83,
      },
      {
        id: "r-16-5",
        minerId: "miner_b0w4e",
        minerUsername: "DeepMining",
        appId: "16",
        rating: 4,
        comment: "High barrier to entry (RTX 3080+, 64GB RAM, 500GB) but rewards are proportionally high. Custom verification means you really need to understand what you're running before jumping in. The Bittensor community is excellent for getting started.",
        timestamp: "2026-03-02",
        helpful: 58,
      },
    ],
    averageRating: 4.7,
    reviewCount: 156,
    monthlyGrowth: 32.1,
    trending: true,
    featured: true,
  },
  {
    id: "17",
    name: "DIMO",
    description: "Decentralized IoT project for vehicles. Share car data and earn DIMO tokens.",
    category: "IoT",
    developer: "Digital Infrastructure Inc",
    developerAddress: "0xDIMO...g3h4",
    icon: "/logos/dimo.png",
    status: "active",
    reputationScore: 87,
    totalMiners: 42000,
    totalEarnings: 890000,
    avgEarningsPerDay: 12.5,
    requirements: {
      cpu: "1 core",
      ram: "2GB",
      storage: "16GB",
    },
    resourceTypes: ["data"],
    rewardToken: "DIMO",
    createdAt: "2024-02-15",
    attestations: 134,
    tags: ["IoT", "Automotive", "Data"],
    consensusMechanism: "PoA",
    verificationMethod: "oracle",
    rewardModel: "time-based",
    slaRequirements: {
      minUptime: 70,
      maxLatency: 5000,
      minBandwidth: 1,
      proofSubmissionInterval: 86400,
      slashingPenalty: 1,
    },
    screenshots: [],
    features: ["Vehicle telemetry", "Trip tracking", "Maintenance alerts"],
    reviews: [
      {
        id: "r-17-1",
        minerId: "miner_p9t5h",
        minerUsername: "CarDataMiner",
        appId: "17",
        rating: 4,
        comment: "Plugged the OBD dongle into my family car — earns DIMO passively while I commute. $12.50/day average is modest but hardware cost is under $50 and maintenance is zero. With 42,000 miners the network effects are strong.",
        timestamp: "2025-08-22",
        helpful: 76,
      },
      {
        id: "r-17-2",
        minerId: "miner_g4m1w",
        minerUsername: "FleetOwner",
        appId: "17",
        rating: 5,
        comment: "Running DIMO on 8 fleet vehicles. The vehicle telemetry data is genuinely valuable to insurance and logistics companies which keeps demand up. Maintenance alerts have actually saved me from costly breakdowns — added utility beyond token rewards.",
        timestamp: "2025-10-14",
        helpful: 61,
      },
      {
        id: "r-17-3",
        minerId: "miner_z2v8s",
        minerUsername: "PassiveIncome",
        appId: "17",
        rating: 4,
        comment: "Easiest DePIN setup I've done. App is polished and trip tracking works flawlessly. Reward model is time-based so consistent driving habits equal consistent income. Oracle verification means the data is actually authenticated.",
        timestamp: "2025-12-01",
        helpful: 48,
      },
      {
        id: "r-17-4",
        minerId: "miner_e6n3d",
        minerUsername: "UberMiner",
        appId: "17",
        rating: 5,
        comment: "Rideshare driver here — I drive 200+ miles per day so DIMO is a perfect income layer. The trip tracking integrates with my existing routing apps and the DIMO token appreciation has made this one of my best investments.",
        timestamp: "2026-01-09",
        helpful: 89,
      },
      {
        id: "r-17-5",
        minerId: "miner_l7c2k",
        minerUsername: "DataDriver",
        appId: "17",
        rating: 3,
        comment: "Concept is solid but DIMO per-vehicle earnings are lower than I hoped. Works best as a secondary income on top of existing driving. The privacy trade-off (sharing vehicle data) is worth considering before joining.",
        timestamp: "2026-02-17",
        helpful: 34,
      },
    ],
    averageRating: 4.2,
    reviewCount: 890,
    monthlyGrowth: 18.5,
    trending: true,
  },
  {
    id: "18",
    name: "Grass",
    description: "Decentralized bandwidth network. Share your unused internet bandwidth and earn GRASS tokens.",
    category: "DePIN",
    developer: "Wynd Labs",
    developerAddress: "0xWYND...i5j6",
    icon: "/logos/grass.jpg",
    status: "active",
    reputationScore: 82,
    totalMiners: 2100000,
    totalEarnings: 5600000,
    avgEarningsPerDay: 8.5,
    requirements: {
      cpu: "1 core",
      ram: "1GB",
      bandwidth: "5 Mbps",
    },
    resourceTypes: ["bandwidth"],
    rewardToken: "GRASS",
    createdAt: "2024-04-01",
    attestations: 89,
    tags: ["Bandwidth", "DePIN", "Passive"],
    consensusMechanism: "PoA",
    verificationMethod: "oracle",
    rewardModel: "time-based",
    slaRequirements: {
      minUptime: 50,
      maxLatency: 2000,
      minBandwidth: 5,
      proofSubmissionInterval: 3600,
      slashingPenalty: 0,
    },
    screenshots: [],
    features: ["Passive income", "Browser extension", "Network scaling"],
    reviews: [
      {
        id: "r-18-1",
        minerId: "miner_y0r8t",
        minerUsername: "GrassRunner",
        appId: "18",
        rating: 5,
        comment: "Install the browser extension, forget about it, collect GRASS. I run it on 4 machines at home and a VPS and the combined earnings are meaningful. 2.1 million miners is proof that the barrier to entry is low enough for mass adoption.",
        timestamp: "2025-07-15",
        helpful: 148,
      },
      {
        id: "r-18-2",
        minerId: "miner_s3u6j",
        minerUsername: "BandwidthSeller",
        appId: "18",
        rating: 4,
        comment: "45% monthly growth is the fastest I've seen in DePIN. GRASS earnings are small per machine but the near-zero hardware and effort requirements make the math work. Running on 12 office computers with management approval — easy passive income.",
        timestamp: "2025-09-28",
        helpful: 117,
      },
      {
        id: "r-18-3",
        minerId: "miner_w5e9c",
        minerUsername: "PassivePile",
        appId: "18",
        rating: 4,
        comment: "The PoA + oracle verification makes sense for bandwidth sharing — it's lightweight enough to not interfere with normal browsing. No slashing penalty is a big deal for newcomers worried about losing funds. Ideal first DePIN protocol.",
        timestamp: "2025-11-11",
        helpful: 93,
      },
      {
        id: "r-18-4",
        minerId: "miner_n8k4f",
        minerUsername: "ScaleOps",
        appId: "18",
        rating: 3,
        comment: "Per-machine earnings are low ($8.50/day average) so you need scale to make it significant. Works fine as a set-and-forget protocol but don't expect life-changing income from a single connection. Best combined with higher-yield protocols.",
        timestamp: "2026-01-21",
        helpful: 72,
      },
      {
        id: "r-18-5",
        minerId: "miner_d1p7m",
        minerUsername: "NetworkLeaser",
        appId: "18",
        rating: 5,
        comment: "Grass is the most accessible DePIN protocol in the market. Any computer with a browser can participate. The time-based model rewards consistent uptime which is easy to achieve. Token launch has been the best performing in my DePIN portfolio.",
        timestamp: "2026-02-08",
        helpful: 104,
      },
    ],
    averageRating: 4.0,
    reviewCount: 3400,
    monthlyGrowth: 45.2,
    trending: true,
  },
  {
    id: "19",
    name: "Worldcoin",
    description: "Global identity and financial project. Operate Orb nodes and earn WLD tokens for proof-of-personhood verification.",
    category: "DePIN",
    developer: "Tools for Humanity",
    developerAddress: "0xWRLD...k7l8",
    icon: "/logos/worldcoin.png",
    status: "active",
    reputationScore: 91,
    totalMiners: 25000,
    totalEarnings: 8900000,
    avgEarningsPerDay: 145.0,
    requirements: {
      gpu: "NVIDIA RTX 3070+",
      cpu: "6 cores",
      ram: "32GB",
      storage: "256GB",
      bandwidth: "100 Mbps",
    },
    resourceTypes: ["compute"],
    rewardToken: "IO",
    createdAt: "2024-03-15",
    attestations: 156,
    tags: ["GPU", "AI", "Cloud"],
    consensusMechanism: "PoW",
    verificationMethod: "tee-attestation",
    attestationRequirements: ["TEE"],
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 95,
      maxLatency: 150,
      minBandwidth: 100,
      proofSubmissionInterval: 300,
      slashingPenalty: 10,
    },
    screenshots: [],
    features: ["GPU clustering", "AI model training", "Inference at scale"],
    reviews: [
      {
        id: "r-19-1",
        minerId: "miner_k1z5t",
        minerUsername: "GPUCluster",
        appId: "19",
        rating: 5,
        comment: "io.net's GPU clustering technology is genuinely novel — my 4 RTX 3080s form a unified cluster that takes on workloads too large for individual GPUs. Earnings of $145/day per node make this the highest-paying GPU protocol I run. 38.7% monthly growth is real.",
        timestamp: "2025-08-03",
        helpful: 134,
      },
      {
        id: "r-19-2",
        minerId: "miner_u7b3x",
        minerUsername: "AIFarmOp",
        appId: "19",
        rating: 5,
        comment: "The AI training demand is insatiable right now and io.net captures it better than any other protocol. TEE attestation ensures my hardware runs legitimate workloads. 25,000 miners and growing fast — this is infrastructure-grade DePIN.",
        timestamp: "2025-10-19",
        helpful: 108,
      },
      {
        id: "r-19-3",
        minerId: "miner_c4w9p",
        minerUsername: "InferenceNode",
        appId: "19",
        rating: 4,
        comment: "Inference at scale is where io.net shines. Per-task rewards mean responsive hardware wins. The 100 Mbps bandwidth requirement is high but necessary for the workload sizes. Setup documentation could be clearer for Docker networking configuration.",
        timestamp: "2025-12-28",
        helpful: 79,
      },
      {
        id: "r-19-4",
        minerId: "miner_r6s2g",
        minerUsername: "RTX3090Rig",
        appId: "19",
        rating: 5,
        comment: "Upgraded from Render Network to io.net six months ago and tripled my IO earnings. The GPU clustering means I take on larger jobs at better rates. Proof of Work verification is straightforward and I've never had a contested submission.",
        timestamp: "2026-01-14",
        helpful: 92,
      },
      {
        id: "r-19-5",
        minerId: "miner_m0j6n",
        minerUsername: "HFTCompute",
        appId: "19",
        rating: 4,
        comment: "Outstanding earnings ceiling if you have the right hardware. RTX 3070 is the minimum and honestly you want more to compete. The IO token economics favor early miners — network is growing fast enough that getting in now makes sense.",
        timestamp: "2026-02-25",
        helpful: 61,
      },
    ],
    averageRating: 4.5,
    reviewCount: 567,
    monthlyGrowth: 38.7,
    trending: true,
    featured: true,
  },
  {
    id: "20",
    name: "Nosana",
    description: "Decentralized CI/CD and GPU compute. Run containerized workloads and earn NOS tokens.",
    category: "Compute",
    developer: "Nosana BV",
    developerAddress: "0xNOSA...m9n0",
    icon: "/logos/nosana.jpg",
    status: "active",
    reputationScore: 88,
    totalMiners: 3200,
    totalEarnings: 780000,
    avgEarningsPerDay: 95.0,
    requirements: {
      gpu: "NVIDIA GTX 1080+",
      cpu: "4 cores",
      ram: "16GB",
      storage: "128GB",
    },
    resourceTypes: ["compute"],
    rewardToken: "NOS",
    createdAt: "2024-02-28",
    attestations: 78,
    tags: ["CI/CD", "GPU", "DevOps"],
    consensusMechanism: "PoS",
    verificationMethod: "on-chain",
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 90,
      maxLatency: 500,
      minBandwidth: 50,
      proofSubmissionInterval: 600,
      slashingPenalty: 8,
    },
    screenshots: [],
    features: ["Container execution", "GPU pipelines", "Solana integration"],
    reviews: [
      {
        id: "r-20-1",
        minerId: "miner_e9v4k",
        minerUsername: "CINode",
        appId: "20",
        rating: 5,
        comment: "Nosana fills a niche nobody else is touching — CI/CD on decentralized GPU. My GTX 1080 runs containerized build pipelines for Web3 projects all day. NOS earnings are strong and the Solana integration means near-instant settlements.",
        timestamp: "2025-09-07",
        helpful: 52,
      },
      {
        id: "r-20-2",
        minerId: "miner_j2n1w",
        minerUsername: "DevOpsMiner",
        appId: "20",
        rating: 4,
        comment: "Solid protocol for GPU miners who want CI/CD workloads instead of AI training. Container execution is sandboxed properly and I've had zero issues with malicious jobs. On-chain verification is fast and transparent.",
        timestamp: "2025-11-04",
        helpful: 39,
      },
      {
        id: "r-20-3",
        minerId: "miner_t5r8f",
        minerUsername: "PipelineRunner",
        appId: "20",
        rating: 4,
        comment: "22.3% monthly growth is accelerating as more Web3 devs discover decentralized CI/CD. The GPU pipeline work is steady and less GPU-intensive than AI training so thermals stay manageable. NOS per-task payments are fair.",
        timestamp: "2026-01-02",
        helpful: 31,
      },
      {
        id: "r-20-4",
        minerId: "miner_b8c5y",
        minerUsername: "BuildFarm",
        appId: "20",
        rating: 5,
        comment: "Running 6 GTX 1080 Ti cards exclusively for Nosana. The build job variety keeps GPU utilization high throughout the day. PoS verification with on-chain records means transparent audit trails — great for professional miner operations.",
        timestamp: "2026-02-12",
        helpful: 44,
      },
    ],
    averageRating: 4.4,
    reviewCount: 89,
    monthlyGrowth: 22.3,
  },
  {
    id: "21",
    name: "Aethir",
    description: "Enterprise-grade GPU-as-a-Service. Contribute idle GPUs to power AI and cloud gaming workloads.",
    category: "Compute",
    developer: "Aethir Foundation",
    developerAddress: "0xAETH...o1p2",
    icon: "/logos/aethir.png",
    status: "active",
    reputationScore: 90,
    totalMiners: 4500,
    totalEarnings: 1200000,
    avgEarningsPerDay: 72.0,
    requirements: {
      cpu: "4 cores",
      ram: "16GB",
      storage: "100GB",
      bandwidth: "50 Mbps",
    },
    resourceTypes: ["compute"],
    rewardToken: "FLT",
    createdAt: "2024-01-10",
    attestations: 112,
    tags: ["Serverless", "WASM", "Compute"],
    consensusMechanism: "DPoS",
    verificationMethod: "zk-proof",
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 95,
      maxLatency: 200,
      minBandwidth: 50,
      proofSubmissionInterval: 300,
      slashingPenalty: 12,
    },
    screenshots: [],
    features: ["WASM runtime", "P2P networking", "Aqua language"],
    reviews: [
      {
        id: "r-21-1",
        minerId: "miner_h4u7s",
        minerUsername: "WASMRunner",
        appId: "21",
        rating: 5,
        comment: "Fluence's WASM runtime is technically impressive — sandboxed serverless functions that can be composed via the Aqua language. My node handles 200+ function invocations per hour and FLT earnings are excellent. ZK-proof verification is trustless.",
        timestamp: "2025-08-25",
        helpful: 57,
      },
      {
        id: "r-21-2",
        minerId: "miner_x0k3d",
        minerUsername: "ServerlessNode",
        appId: "21",
        rating: 4,
        comment: "Impressive compute platform once you understand the Aqua programming model. DPoS consensus keeps the network efficient. 15.8% monthly growth is consistent with the developer adoption I see on their Discord. Hardware requirements are reasonable.",
        timestamp: "2025-10-31",
        helpful: 42,
      },
      {
        id: "r-21-3",
        minerId: "miner_v3m5j",
        minerUsername: "P2PCompute",
        appId: "21",
        rating: 4,
        comment: "Strong technical foundation with genuine innovation in P2P serverless compute. Per-task reward model scales well as function workloads grow. The Aqua language has a learning curve but the community documentation is improving rapidly.",
        timestamp: "2025-12-22",
        helpful: 34,
      },
      {
        id: "r-21-4",
        minerId: "miner_g8t2e",
        minerUsername: "FunctionMiner",
        appId: "21",
        rating: 5,
        comment: "Fluence competes with AWS Lambda but decentralized — that's a massive market. My node earns FLT from web3 applications that need reliable serverless compute without cloud vendor lock-in. This protocol has serious long-term potential.",
        timestamp: "2026-01-28",
        helpful: 48,
      },
    ],
    averageRating: 4.6,
    reviewCount: 134,
    monthlyGrowth: 15.8,
  },
  {
    id: "22",
    name: "Polkadot",
    description: "Multi-chain validation project. Validate and earn DOT.",
    category: "Blockchain",
    developer: "Web3 Foundation",
    developerAddress: "0xDOTS...q3r4",
    icon: "/logos/polkadot.png",
    status: "active",
    reputationScore: 98,
    totalMiners: 12890,
    totalEarnings: 4200000,
    avgEarningsPerDay: 180.5,
    requirements: {
      cpu: "8 cores",
      ram: "32GB",
      storage: "500GB",
      bandwidth: "100 Mbps",
    },
    resourceTypes: ["compute"],
    rewardToken: "DOT",
    createdAt: "2023-11-20",
    attestations: 234,
    tags: ["Validator", "Multi-chain", "Consensus"],
    consensusMechanism: "PoS",
    verificationMethod: "tee-attestation",
    rewardModel: "stake-weighted",
    slaRequirements: {
      minUptime: 99.5,
      maxLatency: 200,
      minBandwidth: 100,
      proofSubmissionInterval: 1200,
      slashingPenalty: 50,
    },
    screenshots: [],
    features: ["Parachain validation", "Staking rewards", "Network security"],
    reviews: [
      {
        id: "r-22-1",
        minerId: "miner_q1f9x",
        minerUsername: "DotValidator",
        appId: "22",
        rating: 5,
        comment: "Running a Polkadot validator is the highest-prestige node operation I've done. The stake-weighted rewards at $180/day are excellent for 8-core hardware. TEE attestation requirement filters out bad actors and the 50% slashing enforces real accountability.",
        timestamp: "2025-07-12",
        helpful: 98,
      },
      {
        id: "r-22-2",
        minerId: "miner_i5b7r",
        minerUsername: "ParachainOp",
        appId: "22",
        rating: 5,
        comment: "Polkadot's multi-chain architecture means my validator secures multiple parachains simultaneously which multiplies reward opportunities. The PoS consensus is battle-tested and the Web3 Foundation team is one of the best in the industry.",
        timestamp: "2025-09-20",
        helpful: 81,
      },
      {
        id: "r-22-3",
        minerId: "miner_d3n0c",
        minerUsername: "StakeMaximizer",
        appId: "22",
        rating: 4,
        comment: "High hardware requirements (8 cores, 32GB, 500GB) and a steep slashing penalty (50%) demand professional infrastructure. But the DOT rewards justify enterprise-grade setup. Network security contribution is real — this protocol matters.",
        timestamp: "2025-11-17",
        helpful: 63,
      },
      {
        id: "r-22-4",
        minerId: "miner_w9j4v",
        minerUsername: "ValidatorSet",
        appId: "22",
        rating: 5,
        comment: "My Polkadot validator earns steady DOT with 4.2% monthly growth — not the fastest but the most reliable. 99.5% uptime requirement keeps the quality bar high. 267 attestations is a testament to years of honest validator operation.",
        timestamp: "2026-01-05",
        helpful: 74,
      },
      {
        id: "r-22-5",
        minerId: "miner_a4e6u",
        minerUsername: "Web3Validator",
        appId: "22",
        rating: 4,
        comment: "Excellent protocol for serious operators. The featured status is well-earned — Polkadot has sustained through multiple bear markets and the validator economics remain strong. Would benefit from better UX tooling for monitoring nomination pools.",
        timestamp: "2026-02-26",
        helpful: 52,
      },
    ],
    averageRating: 4.8,
    reviewCount: 267,
    monthlyGrowth: 4.2,
    featured: true,
  },
  {
    id: "23",
    name: "Starknet",
    description: "Zero-knowledge proof verification. Earn STRK for verifications.",
    category: "AI/ML",
    developer: "StarkWare",
    developerAddress: "0xSTRK...s5t6",
    icon: "/logos/starknet.png",
    status: "active",
    reputationScore: 94,
    totalMiners: 4123,
    totalEarnings: 890000,
    avgEarningsPerDay: 105.8,
    requirements: {
      cpu: "8 cores",
      ram: "32GB",
      storage: "200GB",
    },
    resourceTypes: ["compute"],
    rewardToken: "STRK",
    createdAt: "2024-02-15",
    attestations: 89,
    tags: ["ZK-proofs", "Verification", "AI"],
    consensusMechanism: "Custom",
    verificationMethod: "zk-proof",
    rewardModel: "performance-based",
    slaRequirements: {
      minUptime: 98,
      maxLatency: 300,
      minBandwidth: 50,
      proofSubmissionInterval: 600,
      slashingPenalty: 18,
    },
    screenshots: [],
    features: ["ZK verification", "Proof aggregation", "Performance tracking"],
    reviews: [
      {
        id: "r-23-1",
        minerId: "miner_t7w2k",
        minerUsername: "ZKProver",
        appId: "23",
        rating: 5,
        comment: "ZK proof generation is computationally demanding but STRK rewards are proportionally strong. My 8-core rig earns $105/day running Starknet verification. Proof aggregation batches make the economics better than single-proof protocols.",
        timestamp: "2025-09-03",
        helpful: 63,
      },
      {
        id: "r-23-2",
        minerId: "miner_n2v5y",
        minerUsername: "CryptoproofOps",
        appId: "23",
        rating: 4,
        comment: "Technically sophisticated protocol — you need to understand ZK cryptography basics to diagnose issues. Performance tracking is excellent and the 19.5% monthly growth reflects growing L2 usage on Starknet. High slashing (18%) keeps network honest.",
        timestamp: "2025-11-20",
        helpful: 47,
      },
      {
        id: "r-23-3",
        minerId: "miner_e4r1p",
        minerUsername: "STARKMiner",
        appId: "23",
        rating: 5,
        comment: "Performance-based rewards mean my optimized node consistently out-earns competitors with identical hardware. The ZK verification work is legitimate cryptographic computation which gives me confidence in the protocol's value. STRK has strong fundamentals.",
        timestamp: "2026-01-16",
        helpful: 54,
      },
      {
        id: "r-23-4",
        minerId: "miner_j9c3f",
        minerUsername: "ProofAggregator",
        appId: "23",
        rating: 4,
        comment: "Starknet is positioned as a major L2 scaling solution and running a verification node puts you at the infrastructure layer. 200GB storage for proof data accumulates fast — plan accordingly. The custom consensus is flexible for specialized workloads.",
        timestamp: "2026-02-22",
        helpful: 38,
      },
    ],
    averageRating: 4.5,
    reviewCount: 76,
    monthlyGrowth: 19.5,
    trending: true,
  },
  {
    id: "24",
    name: "Bandwidth Protocol",
    description: "Decentralized bandwidth sharing. Get paid for your connection.",
    category: "Content Delivery",
    developer: "Bandwidth Labs",
    developerAddress: "0xBWDT...u7v8",
    icon: "/logos/bandwidth.png",
    status: "active",
    reputationScore: 89,
    totalMiners: 6543,
    totalEarnings: 720000,
    avgEarningsPerDay: 35.6,
    requirements: {
      bandwidth: "50 Mbps",
      cpu: "2 cores",
      ram: "4GB",
    },
    resourceTypes: ["bandwidth"],
    rewardToken: "BAND",
    createdAt: "2024-03-05",
    attestations: 54,
    tags: ["Bandwidth", "CDN", "P2P"],
    consensusMechanism: "Custom",
    verificationMethod: "on-chain",
    rewardModel: "time-based",
    slaRequirements: {
      minUptime: 90,
      maxLatency: 1000,
      minBandwidth: 50,
      proofSubmissionInterval: 3600,
      slashingPenalty: 4,
    },
    screenshots: [],
    features: ["Bandwidth verification", "Payment channels"],
    reviews: [
      {
        id: "r-24-1",
        minerId: "miner_r5k8n",
        minerUsername: "CDNMiner",
        appId: "24",
        rating: 4,
        comment: "Bandwidth Protocol fills a gap in the CDN space. My fiber connection (500 Mbps) earns BAND tokens for bandwidth I wasn't using. Payment channels mean rewards arrive quickly without waiting for on-chain settlement cycles.",
        timestamp: "2025-10-08",
        helpful: 34,
      },
      {
        id: "r-24-2",
        minerId: "miner_m0g4s",
        minerUsername: "ContentDelivery",
        appId: "24",
        rating: 5,
        comment: "25.8% monthly growth is reflected in steadily increasing BAND earnings. The bandwidth verification process is transparent and dispute-free in my 6 months running. Requires only 2 cores and 4GB RAM so I run it alongside heavier protocols.",
        timestamp: "2025-12-16",
        helpful: 28,
      },
      {
        id: "r-24-3",
        minerId: "miner_b3p7v",
        minerUsername: "P2PRelay",
        appId: "24",
        rating: 4,
        comment: "Good supplementary income for anyone with excess upstream bandwidth. Time-based rewards are predictable and the 4% slashing penalty is low risk. Would like to see more analytics on which content types drive the highest earnings.",
        timestamp: "2026-01-31",
        helpful: 21,
      },
      {
        id: "r-24-4",
        minerId: "miner_x8e2t",
        minerUsername: "NetNode",
        appId: "24",
        rating: 3,
        comment: "Honest review: earnings are modest at $35/day average. The 25.8% growth is real but from a small base. Best suited for people with large bandwidth pipes they're not using. The on-chain verification is clean but payment amounts are small per node.",
        timestamp: "2026-03-05",
        helpful: 17,
      },
    ],
    averageRating: 4.2,
    reviewCount: 45,
    monthlyGrowth: 25.8,
    trending: true,
  },
  {
    id: "25",
    name: "Polygon",
    description: "Ethereum scaling solution. Run validator nodes and earn MATIC through proof-of-stake consensus.",
    category: "Compute",
    developer: "Polygon Labs",
    developerAddress: "0xPOLY...w9x0",
    icon: "/logos/polygon.png",
    status: "active",
    reputationScore: 92,
    totalMiners: 2876,
    totalEarnings: 560000,
    avgEarningsPerDay: 52.3,
    requirements: {
      cpu: "4 cores",
      ram: "8GB",
      storage: "50GB",
    },
    resourceTypes: ["data"],
    rewardToken: "NYMPH",
    createdAt: "2024-02-20",
    attestations: 67,
    tags: ["Privacy", "Data", "Encryption"],
    consensusMechanism: "PoA",
    verificationMethod: "multi-sig",
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 95,
      maxLatency: 400,
      minBandwidth: 20,
      proofSubmissionInterval: 7200,
      slashingPenalty: 6,
    },
    screenshots: [],
    features: ["Privacy protocols", "Data encryption", "Anonymity"],
    reviews: [
      {
        id: "r-25-1",
        minerId: "miner_a7j3c",
        minerUsername: "PrivacyNode",
        appId: "25",
        rating: 5,
        comment: "Nymph fills a real need — privacy-preserving data monetization is the future as regulations tighten. Multi-sig verification ensures data provenance without exposing raw data. My node earns NYMPH from enterprise clients paying premium for anonymized datasets.",
        timestamp: "2025-09-15",
        helpful: 41,
      },
      {
        id: "r-25-2",
        minerId: "miner_s1w6n",
        minerUsername: "CryptoPrivate",
        appId: "25",
        rating: 4,
        comment: "Good protocol for the privacy-focused DePIN niche. PoA consensus and multi-sig verification are solid choices for a data sovereignty platform. Per-task rewards are fair given the lightweight hardware requirements (4 cores, 8GB).",
        timestamp: "2025-11-28",
        helpful: 30,
      },
      {
        id: "r-25-3",
        minerId: "miner_k4u9b",
        minerUsername: "AnonMiner",
        appId: "25",
        rating: 4,
        comment: "9.4% monthly growth is steady if not spectacular. The encryption layer adds real value for clients who need GDPR-compliant data pipelines. Would benefit from more marketing to enterprise buyers who haven't discovered decentralized data markets yet.",
        timestamp: "2026-01-23",
        helpful: 25,
      },
      {
        id: "r-25-4",
        minerId: "miner_v8d2p",
        minerUsername: "DataSovereign",
        appId: "25",
        rating: 5,
        comment: "Running Nymph for 7 months. The privacy protocols are technically sound and the anonymity guarantees have been independently verified. Earnings are consistent and the market for privacy-first data networks is only going to grow.",
        timestamp: "2026-02-16",
        helpful: 36,
      },
    ],
    averageRating: 4.4,
    reviewCount: 58,
    monthlyGrowth: 9.4,
  },
  {
    id: "26",
    name: "Flux Network",
    description: "Decentralized cloud infrastructure. Host applications.",
    category: "Compute",
    developer: "Flux Labs",
    developerAddress: "0xFLUX...y1z2",
    icon: "/logos/flux.png",
    status: "active",
    reputationScore: 93,
    totalMiners: 7654,
    totalEarnings: 1340000,
    avgEarningsPerDay: 78.9,
    requirements: {
      cpu: "8 cores",
      ram: "32GB",
      storage: "500GB",
      bandwidth: "100 Mbps",
    },
    resourceTypes: ["compute", "storage"],
    rewardToken: "FLUX",
    createdAt: "2024-01-12",
    attestations: 112,
    tags: ["Cloud", "Hosting", "Docker"],
    consensusMechanism: "PoW",
    verificationMethod: "merkle-proof",
    rewardModel: "time-based",
    slaRequirements: {
      minUptime: 97,
      maxLatency: 300,
      minBandwidth: 100,
      proofSubmissionInterval: 900,
      slashingPenalty: 10,
    },
    screenshots: [],
    features: ["Container hosting", "Load balancing", "Auto-scaling"],
    reviews: [
      {
        id: "r-26-1",
        minerId: "miner_c6m4r",
        minerUsername: "FluxNode",
        appId: "26",
        rating: 5,
        comment: "Flux is the best decentralized cloud infrastructure I've hosted on. Container deployment is seamless, load balancing works as advertised, and FLUX earnings are strong at $78/day. PoW verification keeps the network secure against Sybil attacks.",
        timestamp: "2025-08-14",
        helpful: 69,
      },
      {
        id: "r-26-2",
        minerId: "miner_f9x1w",
        minerUsername: "DockerMiner",
        appId: "26",
        rating: 5,
        comment: "Running Flux on a dedicated home server (8 cores, 32GB, 500GB). Auto-scaling handles traffic spikes automatically and the load balancer distributes jobs efficiently. 7.3% monthly growth is stable and the FLUX token has shown strong fundamentals.",
        timestamp: "2025-10-22",
        helpful: 54,
      },
      {
        id: "r-26-3",
        minerId: "miner_h7n5k",
        minerUsername: "CloudRunner",
        appId: "26",
        rating: 4,
        comment: "Excellent protocol for repurposing server hardware. The 97% uptime SLA is achievable with a UPS and stable internet. Merkle-proof verification is transparent and I've never had an earnings dispute in 10 months of operation.",
        timestamp: "2025-12-11",
        helpful: 41,
      },
      {
        id: "r-26-4",
        minerId: "miner_p2v8c",
        minerUsername: "InfraOps",
        appId: "26",
        rating: 4,
        comment: "Time-based reward model rewards reliability which suits my always-on infrastructure. The bandwidth requirement (100 Mbps) is the steepest constraint but necessary for container workloads. Flux competes directly with AWS and that's a huge market.",
        timestamp: "2026-01-29",
        helpful: 36,
      },
    ],
    averageRating: 4.7,
    reviewCount: 134,
    monthlyGrowth: 7.3,
  },
  {
    id: "27",
    name: "Fetch.ai",
    description: "Autonomous AI agents for DeFi, supply chain, and mobility. Run agent nodes and earn FET tokens.",
    category: "AI/ML",
    developer: "Fetch.ai Foundation",
    developerAddress: "0xFETH...a3b4",
    icon: "/logos/fetchai.png",
    status: "active",
    reputationScore: 90,
    totalMiners: 3245,
    totalEarnings: 420000,
    avgEarningsPerDay: 38.5,
    requirements: {
      cpu: "2 cores",
      ram: "4GB",
      bandwidth: "10 Mbps",
    },
    resourceTypes: ["data"],
    rewardToken: "SENT",
    createdAt: "2024-03-08",
    attestations: 45,
    tags: ["Monitoring", "Analytics", "Nodes"],
    consensusMechanism: "PoA",
    verificationMethod: "on-chain",
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 92,
      maxLatency: 1000,
      minBandwidth: 10,
      proofSubmissionInterval: 3600,
      slashingPenalty: 2,
    },
    screenshots: [],
    features: ["Network monitoring", "Real-time alerts", "Analytics dashboard"],
    reviews: [
      {
        id: "r-27-1",
        minerId: "miner_d5y3t",
        minerUsername: "WatchdogNode",
        appId: "27",
        rating: 4,
        comment: "Sentinel is a unique niche — earning SENT for monitoring other nodes rather than serving compute or storage. My monitoring node runs on minimal hardware (2 cores, 4GB) and the per-task rewards are solid for the resource investment.",
        timestamp: "2025-09-25",
        helpful: 29,
      },
      {
        id: "r-27-2",
        minerId: "miner_q8b6u",
        minerUsername: "AlertMiner",
        appId: "27",
        rating: 5,
        comment: "13.7% monthly growth reflects the growing demand for decentralized network monitoring. Real-time alerts are genuinely useful — I've caught downtime on monitored nodes before their operators noticed. PoA verification keeps monitoring tasks lightweight.",
        timestamp: "2025-11-14",
        helpful: 37,
      },
      {
        id: "r-27-3",
        minerId: "miner_z1k5n",
        minerUsername: "MonitorOps",
        appId: "27",
        rating: 4,
        comment: "Low hardware barrier makes this great for entry-level miners or as a supplementary income alongside heavier protocols. The analytics dashboard is well-designed and the on-chain verification ensures honest reporting. No slashing history in 5 months.",
        timestamp: "2026-01-11",
        helpful: 22,
      },
      {
        id: "r-27-4",
        minerId: "miner_r3e7p",
        minerUsername: "NetGuardian",
        appId: "27",
        rating: 4,
        comment: "Solid protocol concept with a clear value proposition. The DePIN network monitoring space is underserved and Sentinel is positioned well. Earnings are modest at $38.50/day but the low hardware cost means the margin percentage is excellent.",
        timestamp: "2026-02-28",
        helpful: 18,
      },
    ],
    averageRating: 4.3,
    reviewCount: 41,
    monthlyGrowth: 13.7,
  },
  {
    id: "28",
    name: "DockHive",
    description: "Decentralized cloud hosting protocol for Web3 and Web2 applications. Deploy, scale, and own your infrastructure. Miners provide compute, storage, and GPU resources to power app hosting, managed databases, virtual machines, and object storage across a global infrastructure with no single point of failure.",
    category: "Compute",
    developer: "Hive Innovation Lab",
    developerAddress: "0xDOCK...h1v3",
    icon: "/logos/dockhive.jpg",
    status: "active",
    reputationScore: 91,
    totalMiners: 3420,
    totalEarnings: 890000,
    avgEarningsPerDay: 52.8,
    requirements: {
      cpu: "4 cores",
      ram: "16GB",
      storage: "500GB SSD",
      bandwidth: "100 Mbps",
    },
    resourceTypes: ["compute", "storage"],
    rewardToken: "DOCK",
    createdAt: "2025-06-10",
    attestations: 89,
    requiredAttestations: 3,
    consensusMechanism: "Proof of Uptime",
    verificationMethod: "Container Health Check",
    rewardModel: "Per-container-hour",
    minStake: 200,
    minRewardPerTask: 0.08,
    maxRewardPerTask: 0.35,
    rewardSplitMiner: 78,
    rewardSplitDeveloper: 15,
    rewardSplitTreasury: 7,
    sla: {
      minUptime: 99.5,
      maxLatency: 200,
      minBandwidth: 50,
      proofSubmissionInterval: 1800,
      slashingPenalty: 3,
    },
    screenshots: [],
    features: ["App hosting with one-click deploy", "Managed Postgres databases", "GPU and CPU virtual machines (DVMs)", "Decentralized object storage (Hive Buckets)", "Cloud Genesis SDK for Web2/Web3", "60% cost savings vs centralized cloud"],
    reviews: [
      {
        id: "r-28-1",
        minerId: "miner_k8s01",
        minerUsername: "ContainerKing",
        appId: "28",
        rating: 5,
        comment: "DockHive is exactly what the decentralized compute space needed. My 4-core server earns consistent DOCK rewards running developer containers. The health check verification is clever and the uptime SLA keeps everyone honest.",
        timestamp: "2026-01-15",
        helpful: 34,
      },
      {
        id: "r-28-2",
        minerId: "miner_gpu99",
        minerUsername: "CloudMiner",
        appId: "28",
        rating: 4,
        comment: "Running a DVM node with GPU. The Web3-ready hosting angle is smart. Developers deploy their dApps on my hardware and I earn DOCK. Privacy-first approach with end-to-end encryption gives me confidence in what's running on my machine.",
        timestamp: "2026-02-20",
        helpful: 22,
      },
    ],
    averageRating: 4.6,
    reviewCount: 52,
    monthlyGrowth: 22.4,
  },
  {
    id: "29",
    name: "TIWA",
    description: "Decentralized AI-powered knowledge project. Miners contribute compute resources to power AskTiwa, an intelligent assistant that processes natural language queries across decentralized infrastructure. The project distributes AI inference workloads across participating nodes, ensuring fast response times and data privacy.",
    category: "AI/ML",
    developer: "TIWA Labs",
    developerAddress: "0xTIWA...g3o2",
    icon: "/logos/tiwa.png",
    status: "active",
    reputationScore: 88,
    totalMiners: 5670,
    totalEarnings: 1230000,
    avgEarningsPerDay: 38.2,
    requirements: {
      cpu: "4 cores",
      ram: "16GB",
      gpu: "8GB+ VRAM recommended",
      bandwidth: "50 Mbps",
    },
    resourceTypes: ["compute", "data"],
    rewardToken: "TIWA",
    createdAt: "2025-08-22",
    attestations: 67,
    requiredAttestations: 3,
    consensusMechanism: "Proof of Inference",
    verificationMethod: "Response Validation",
    rewardModel: "Per-query",
    minStake: 100,
    minRewardPerTask: 0.03,
    maxRewardPerTask: 0.15,
    rewardSplitMiner: 80,
    rewardSplitDeveloper: 12,
    rewardSplitTreasury: 8,
    sla: {
      minUptime: 95,
      maxLatency: 2000,
      minBandwidth: 10,
      proofSubmissionInterval: 7200,
      slashingPenalty: 1.5,
    },
    screenshots: [],
    features: ["Distributed AI inference", "Natural language processing", "Privacy-preserving queries", "Real-time knowledge retrieval", "Multi-model support", "Edge computing optimization"],
    reviews: [
      {
        id: "r-29-1",
        minerId: "miner_geo42",
        minerUsername: "InferenceNode",
        appId: "29",
        rating: 4,
        comment: "TIWA is doing something genuinely new. Running an inference node from my GPU rig and earning TIWA for processing AI queries. The per-query reward model means busier hours pay better, and the privacy-preserving approach gives me confidence in the workloads.",
        timestamp: "2026-02-10",
        helpful: 27,
      },
    ],
    averageRating: 4.2,
    reviewCount: 38,
    monthlyGrowth: 18.9,
  },
  {
    id: "30",
    name: "Atum",
    description: "Your gateway to a secure, decentralized, and sustainable future. Atum is building a privacy-first ecosystem where data is a user's asset, not a commodity. Miners power Atum's decentralized search engine, node infrastructure, and upcoming decentralized OS through distributed compute and storage. The project emphasizes green energy and carbon-neutral operations.",
    category: "Compute",
    developer: "Atum Software",
    developerAddress: "0xATUM...r5s4",
    icon: "/logos/atum.jpg",
    status: "active",
    reputationScore: 94,
    totalMiners: 2180,
    totalEarnings: 2100000,
    avgEarningsPerDay: 78.5,
    requirements: {
      cpu: "8 cores",
      ram: "32GB",
      storage: "1TB SSD",
      gpu: "NVIDIA RTX 4090 or equivalent",
      bandwidth: "200 Mbps",
    },
    resourceTypes: ["compute"],
    rewardToken: "ATUM",
    createdAt: "2025-04-18",
    attestations: 112,
    requiredAttestations: 3,
    consensusMechanism: "Proof of Training",
    verificationMethod: "Gradient Verification",
    rewardModel: "Per-epoch",
    minStake: 500,
    minRewardPerTask: 0.5,
    maxRewardPerTask: 2.0,
    rewardSplitMiner: 75,
    rewardSplitDeveloper: 18,
    rewardSplitTreasury: 7,
    sla: {
      minUptime: 99,
      maxLatency: 500,
      minBandwidth: 100,
      proofSubmissionInterval: 3600,
      slashingPenalty: 5,
    },
    screenshots: [],
    features: ["Decentralized search engine", "Privacy-first architecture", "Node infrastructure (DePin)", "Green energy commitment", "Decentralized OS (coming)", "DAO governance", "Carbon-neutral mining"],
    reviews: [
      {
        id: "r-30-1",
        minerId: "miner_gpu77",
        minerUsername: "DeepMiner",
        appId: "30",
        rating: 5,
        comment: "Atum's vision of data ownership is compelling and the node rewards are solid. Running a search node that powers their decentralized search engine. The green energy focus is a nice touch. High stake but the returns justify it.",
        timestamp: "2026-03-01",
        helpful: 45,
      },
    ],
    averageRating: 4.7,
    reviewCount: 29,
    monthlyGrowth: 31.2,
  },
]

export const mockMiner: Miner = {
  id: "miner-1",
  address: "0xabcd...ef01",
  username: "MinerPro2024",
  reputationScore: 87,
  totalEarnings: 15420.5,
  activeSubscriptions: 3,
  joinedAt: "2024-01-01",
  hardware: {
    cpu: "AMD Ryzen 9 5950X",
    gpu: "NVIDIA RTX 4090",
    ram: "64GB DDR4",
    storage: "2TB NVMe SSD",
  },
}

export const mockSubscriptions: Subscription[] = [
  {
    id: "sub-1",
    minerId: "miner-1",
    appId: "2",
    status: "active",
    startedAt: "2024-03-01",
    totalEarned: 8750.25,
    tasksCompleted: 1245,
    uptime: 98.5,
  },
  {
    id: "sub-2",
    minerId: "miner-1",
    appId: "1",
    status: "active",
    startedAt: "2024-02-15",
    totalEarned: 4320.75,
    tasksCompleted: 892,
    uptime: 99.2,
  },
  {
    id: "sub-3",
    minerId: "miner-1",
    appId: "6",
    status: "active",
    startedAt: "2024-03-10",
    totalEarned: 2349.5,
    tasksCompleted: 456,
    uptime: 97.8,
  },
]

// User subscriptions with status for subscription management page
export const mockUserSubscriptions = [
  {
    id: "usub-1",
    appId: "1",
    status: "active" as const,
    plan: "pro",
    nextBillingDate: "2026-02-15",
    startedAt: "2024-02-15",
    totalEarned: 4320.75,
    currentMonthEarnings: 892.50,
    uptime: 99.2,
  },
  {
    id: "usub-2",
    appId: "2",
    status: "active" as const,
    plan: "standard",
    nextBillingDate: "2026-02-01",
    startedAt: "2024-03-01",
    totalEarned: 8750.25,
    currentMonthEarnings: 1245.00,
    uptime: 98.5,
  },
  {
    id: "usub-3",
    appId: "3",
    status: "paused" as const,
    plan: "standard",
    nextBillingDate: "2026-02-20",
    startedAt: "2024-01-10",
    totalEarned: 2100.50,
    currentMonthEarnings: 0,
    uptime: 0,
    pausedAt: "2026-01-20",
    pauseReason: "Hardware maintenance",
  },
  {
    id: "usub-4",
    appId: "6",
    status: "active" as const,
    plan: "pro",
    nextBillingDate: "2026-02-10",
    startedAt: "2024-03-10",
    totalEarned: 2349.50,
    currentMonthEarnings: 456.00,
    uptime: 97.8,
  },
  {
    id: "usub-5",
    appId: "4",
    status: "expired" as const,
    plan: "standard",
    startedAt: "2024-01-01",
    expiredAt: "2025-12-01",
    totalEarned: 1250.00,
    currentMonthEarnings: 0,
    uptime: 0,
  },
]

export const mockMiningProfiles: MiningProfile[] = [
  {
    id: "profile-1",
    appId: "1",
    version: "1.2.0",
    taskDomain: "network-coverage",
    consensusMechanism: "PoC",
    verificationMethod: "on-chain",
    rewardModel: "time-based",
    slaRequirements: {
      minUptime: 95,
      maxLatency: 500,
      minBandwidth: 10,
      proofSubmissionInterval: 3600,
      slashingPenalty: 5,
    },
    runtimeConfig: {
      containerType: "docker",
      entrypoint: "/app/helium-miner",
      environment: {
        NETWORK: "mainnet",
        REGION: "auto",
      },
    },
    networkConfig: {
      protocol: "grpc",
      port: 8080,
      endpoints: ["api.helium.io"],
    },
    createdAt: "2024-01-15",
    updatedAt: "2024-03-01",
    status: "active",
  },
  {
    id: "profile-2",
    appId: "2",
    version: "2.1.5",
    taskDomain: "compute-inference",
    consensusMechanism: "PoW",
    verificationMethod: "merkle-proof",
    rewardModel: "per-task",
    slaRequirements: {
      minUptime: 98,
      maxLatency: 200,
      minBandwidth: 50,
      proofSubmissionInterval: 300,
      slashingPenalty: 10,
    },
    runtimeConfig: {
      containerType: "docker",
      entrypoint: "/app/render-worker",
      environment: {
        GPU_MODE: "cuda",
        MAX_CONCURRENT_TASKS: "4",
      },
    },
    networkConfig: {
      protocol: "websocket",
      port: 9090,
      endpoints: ["ws.render.network"],
    },
    createdAt: "2024-02-01",
    updatedAt: "2024-03-15",
    status: "active",
  },
  {
    id: "profile-3",
    appId: "3",
    version: "1.0.8",
    taskDomain: "data-storage",
    consensusMechanism: "PoST",
    verificationMethod: "zk-proof",
    rewardModel: "performance-based",
    slaRequirements: {
      minUptime: 99,
      maxLatency: 100,
      minBandwidth: 100,
      proofSubmissionInterval: 1800,
      slashingPenalty: 15,
    },
    runtimeConfig: {
      containerType: "docker",
      entrypoint: "/app/lotus-miner",
      environment: {
        LOTUS_MINER_PATH: "/data",
        FIL_PROOFS_PARAMETER_CACHE: "/var/tmp/filecoin-proof-parameters",
      },
    },
    networkConfig: {
      protocol: "http",
      port: 2345,
      endpoints: ["api.filecoin.io"],
    },
    createdAt: "2024-01-10",
    updatedAt: "2024-02-28",
    status: "active",
  },
]

export const mockDeveloperAnalytics: Record<string, DeveloperAnalytics> = {
  "1": {
    appId: "1",
    totalMiners: 12453,
    activeMiners: 11892,
    totalTasksSubmitted: 2450000,
    totalTasksCompleted: 2398500,
    totalTasksFailed: 51500,
    avgProofSubmissionTime: 3450,
    avgTaskCompletionTime: 1800,
    totalRewardsDistributed: 2450000,
    slashingEvents: 23,
    uptimePercentage: 97.9,
    period: "30d",
  },
  "2": {
    appId: "2",
    totalMiners: 8932,
    activeMiners: 8765,
    totalTasksSubmitted: 1890000,
    totalTasksCompleted: 1870200,
    totalTasksFailed: 19800,
    avgProofSubmissionTime: 285,
    avgTaskCompletionTime: 450,
    totalRewardsDistributed: 1890000,
    slashingEvents: 12,
    uptimePercentage: 98.9,
    period: "30d",
  },
  "3": {
    appId: "3",
    totalMiners: 15678,
    activeMiners: 15523,
    totalTasksSubmitted: 3200000,
    totalTasksCompleted: 3168000,
    totalTasksFailed: 32000,
    avgProofSubmissionTime: 1750,
    avgTaskCompletionTime: 3600,
    totalRewardsDistributed: 3200000,
    slashingEvents: 8,
    uptimePercentage: 99.0,
    period: "30d",
  },
}

export const mockDevelopers: Developer[] = [
  {
    id: "dev-1",
    address: "0xHELI...a1b2",
    username: "HeliumFoundation",
    email: "team@helium.com",
    company: "Helium Foundation",
    website: "https://helium.com",
    avatar: "/logos/helium.png",
    verified: true,
    totalApps: 1,
    totalMiners: 12453,
    reputationScore: 98,
    joinedAt: "2023-01-15",
    bio: "Building the largest decentralized wireless network.",
    socialLinks: {
      twitter: "helium",
      discord: "helium",
      github: "helium",
    },
  },
  {
    id: "dev-2",
    address: "0xRNDR...c3d4",
    username: "RenderFoundation",
    email: "team@rendernetwork.com",
    company: "Render Foundation",
    website: "https://rendernetwork.com",
    avatar: "/logos/render.png",
    verified: true,
    totalApps: 1,
    totalMiners: 8932,
    reputationScore: 95,
    joinedAt: "2023-02-01",
    bio: "Distributed GPU rendering platform for 3D and AI workloads.",
    socialLinks: {
      twitter: "rendernetwork",
      discord: "render",
      github: "rendernetwork",
    },
  },
  {
    id: "dev-3",
    address: "0xFILE...e5f6",
    username: "ProtocolLabs",
    email: "team@protocol.ai",
    company: "Protocol Labs",
    website: "https://protocol.ai",
    avatar: "/logos/filecoin.png",
    verified: true,
    totalApps: 1,
    totalMiners: 15678,
    reputationScore: 97,
    joinedAt: "2023-01-10",
    bio: "Building distributed systems for humanity. Creators of Filecoin and IPFS.",
    socialLinks: {
      twitter: "protocollabs",
      github: "protocol",
    },
  },
]

export const mockProofSubmissions: ProofSubmission[] = [
  {
    id: "proof-1",
    subscriptionId: "sub-1",
    minerId: "miner-1",
    appId: "2",
    status: "verified",
    submittedAt: "2024-03-15T10:30:00Z",
    verifiedAt: "2024-03-15T10:35:00Z",
    reward: 125.5,
    hash: "0xabcd1234567890abcd1234567890abcd",
  },
  {
    id: "proof-2",
    subscriptionId: "sub-1",
    minerId: "miner-1",
    appId: "2",
    status: "pending",
    submittedAt: "2024-03-15T11:00:00Z",
    reward: 125.5,
    hash: "0xbcde2345678901bcde2345678901bcde",
  },
  {
    id: "proof-3",
    subscriptionId: "sub-2",
    minerId: "miner-1",
    appId: "1",
    status: "verified",
    submittedAt: "2024-03-15T09:45:00Z",
    verifiedAt: "2024-03-15T10:00:00Z",
    reward: 45.25,
    hash: "0xcdef3456789012cdef3456789012cdef",
  },
]

export const mockWithdrawals: Withdrawal[] = [
  {
    id: "withdraw-1",
    minerId: "miner-1",
    amount: 5000,
    status: "completed",
    requestedAt: "2024-03-01T12:00:00Z",
    completedAt: "2024-03-03T14:30:00Z",
    txHash: "0x123456789abcdef",
    walletAddress: "0xabcd...ef01",
    fee: 2.5,
  },
  {
    id: "withdraw-2",
    minerId: "miner-1",
    amount: 3000,
    status: "processing",
    requestedAt: "2024-03-15T08:00:00Z",
    walletAddress: "0xabcd...ef01",
    fee: 1.5,
  },
]

export const mockReferrals: Referral[] = [
  {
    id: "ref-1",
    referrer: "miner-1",
    referred: "miner-2",
    status: "completed",
    reward: 100,
    createdAt: "2024-02-15T10:00:00Z",
    completedAt: "2024-02-20T08:00:00Z",
  },
  {
    id: "ref-2",
    referrer: "miner-1",
    referred: "miner-3",
    status: "pending",
    reward: 100,
    createdAt: "2024-03-10T15:30:00Z",
  },
]

export const mockHardwareProfiles: HardwareProfile[] = [
  {
    id: "hw-1",
    minerId: "miner-1",
    gpuModel: "NVIDIA RTX 4090",
    gpuVram: 24,
    cpuCores: 16,
    cpuThreads: 32,
    ramGb: 128,
    storageGb: 2000,
    networkMbps: 1000,
    benchmarkScore: 98,
  },
  {
    id: "hw-2",
    minerId: "miner-2",
    gpuModel: "NVIDIA RTX 3080",
    gpuVram: 10,
    cpuCores: 8,
    cpuThreads: 16,
    ramGb: 64,
    storageGb: 1000,
    networkMbps: 500,
    benchmarkScore: 85,
  },
  {
    id: "hw-3",
    minerId: "miner-3",
    cpuCores: 4,
    cpuThreads: 8,
    ramGb: 16,
    storageGb: 500,
    networkMbps: 100,
    benchmarkScore: 62,
  },
]

export const mockProofDetails: ProofDetail[] = [
  {
    id: "proof-detail-1",
    subscriptionId: "sub-1",
    appId: "2",
    minerId: "miner-1",
    proofData: "proof_data_hash_abc123",
    status: "verified",
    submittedAt: "2024-03-15T10:30:00Z",
    verifiedAt: "2024-03-15T10:35:00Z",
    verifierNode: "validator-node-5",
    expectedEarning: 125.5,
    actualEarning: 125.5,
    verificationTime: 300000, // 5 minutes in ms
  },
  {
    id: "proof-detail-2",
    subscriptionId: "sub-1",
    appId: "2",
    minerId: "miner-1",
    proofData: "proof_data_hash_bcd234",
    status: "pending",
    submittedAt: "2024-03-15T11:00:00Z",
    verifierNode: undefined,
    expectedEarning: 125.5,
    verificationTime: 0,
  },
  {
    id: "proof-detail-3",
    subscriptionId: "sub-1",
    appId: "2",
    minerId: "miner-1",
    proofData: "proof_data_hash_cde345",
    status: "rejected",
    submittedAt: "2024-03-15T09:15:00Z",
    verifiedAt: "2024-03-15T09:20:00Z",
    verifierNode: "validator-node-2",
    expectedEarning: 125.5,
    rejectionReason: "Invalid consensus parameters",
    verificationTime: 300000,
  },
]

export const mockCollateralInfo: CollateralInfo[] = [
  {
    appId: "1",
    minerId: "miner-1",
    amountRequired: 1000,
    amountLocked: 1000,
    unlockDate: "2024-04-15T00:00:00Z",
    slashingHistory: [
      {
        id: "slash-1",
        timestamp: "2024-03-10T14:30:00Z",
        amount: 50,
        reason: "Failed proof verification - consensus mismatch",
        recoveryPath: "Maintain 100% uptime for 7 days to recover reputation",
      },
    ],
    status: "healthy",
    marginCallRisk: 5,
  },
  {
    appId: "2",
    minerId: "miner-1",
    amountRequired: 2000,
    amountLocked: 2000,
    unlockDate: "2024-05-01T00:00:00Z",
    slashingHistory: [],
    status: "healthy",
    marginCallRisk: 2,
  },
  {
    appId: "3",
    minerId: "miner-1",
    amountRequired: 500,
    amountLocked: 500,
    unlockDate: "2024-03-30T00:00:00Z",
    slashingHistory: [],
    status: "warning",
    marginCallRisk: 45,
  },
]

export const mockMiningProfileTrustScores: MiningProfileTrustScore[] = [
  {
    appId: "1",
    overallScore: 98,
    developerTrackRecord: 98,
    networkSecurity: 97,
    consensusHealth: 99,
    communityVotes: 95,
    trendingDirection: "stable",
    redFlags: [],
    certificationLevel: "platinum",
  },
  {
    appId: "2",
    overallScore: 95,
    developerTrackRecord: 96,
    networkSecurity: 94,
    consensusHealth: 93,
    communityVotes: 92,
    trendingDirection: "improving",
    redFlags: [],
    certificationLevel: "gold",
  },
  {
    appId: "3",
    overallScore: 78,
    developerTrackRecord: 70,
    networkSecurity: 75,
    consensusHealth: 82,
    communityVotes: 65,
    trendingDirection: "declining",
    redFlags: ["Recent slashing events", "Below average uptime"],
    certificationLevel: "verified",
  },
]

export const mockProofStats: ProofStats[] = [
  {
    totalSubmitted: 450,
    totalVerified: 435,
    totalRejected: 15,
    successRate: 96.7,
    averageVerificationTime: 285000, // ~5 minutes
    rejectionReasons: {
      "consensus-mismatch": 8,
      "invalid-format": 4,
      timeout: 3,
    },
  },
]
